.. |xscope_fileio| replace:: ``xscope_fileio``
.. |xtc_tools_version| replace:: 15.3.0
.. |python_version|    replace:: 3.10
.. |cmake_version|     replace:: 3.21

.. _Python:                     https://www.python.org/
.. _CMAKE:                      https://cmake.org/cmake/help/latest/
.. _XMOS Website:               https://www.xmos.com/libraries
.. _xscope_fileio Repository:   https://www.github.com/xmos/xscope_fileio
.. _xscope_fileio Doc Source:   www.github.com/xmos/xscope_fileio/docs
.. _XMOS Evaluation Board:      https://www.xmos.com/xk-evk-xu316
